### PR TITLE
Update dependency management

### PR DESCRIPTION
**Pull request by helrond**
Does the usual dependency management things:
- Adds a dependabot config
- Splits and updates dependencies
- Updates pre-commit configs
- Do Django 3 stuff.

I also did a few other things to improve the overall dev infrastructure:
- Remove libra as a submodule
- Remove fixtures from tests, since initial data is created via a migration
- Make the default Dockerfile load just Zodiac, not all the submodules.

### CODE REVIEW

**Review by p-galligan — COMMENTED** [review]
I got a duplicate key error when standing up zodiac. It stood up successfully and tests passed.

zodiac-db_1   | 2021-07-14 14:41:30.217 UTC [32] STATEMENT:  INSERT INTO "gateway_source" ("user_id", "apikey") VALUES (2, 'aurorakey') RETURNING "gateway_source"."id"
zodiac-web_1  | Traceback (most recent call last):
zodiac-web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
zodiac-web_1  |     return self.cursor.execute(sql, params)
zodiac-web_1  | psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "gateway_source_user_id_key"
zodiac-web_1  | DETAIL:  Key (user_id)=(2) already exists.

**Comment by helrond** [comment]
@p-galligan where is that error originating? I'm guessing the `setup_services` call in `entrypoint.sh` (line 16) but would be good to confirm.

**Comment by p-galligan** [comment]
> @p-galligan where is that error originating? I'm guessing the `setup_services` call in `entrypoint.sh` (line 16) but would be good to confirm.

@helrond Yes, can confirm that it's setting up the services. Error shows up right after "Created users."

**Comment by helrond** [comment]
Ok that's super useful - I added a better filtering statement, but would be curious if anyone else can reproduce this, either consistently or inconsistently.

**Comment by bonniegee** [comment]
I got a different error than @p-galligan , but at the same point:

```
zodiac-web_1  | Created users
zodiac-web_1  | Traceback (most recent call last):
zodiac-web_1  |   File "manage.py", line 15, in <module>
zodiac-web_1  |     execute_from_command_line(sys.argv)
zodiac-web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
zodiac-web_1  |     utility.execute()
zodiac-web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 413, in execute
zodiac-web_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
zodiac-web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 354, in run_from_argv
zodiac-web_1  |     self.execute(*args, **cmd_options)
zodiac-web_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 398, in execute
zodiac-web_1  |     output = self.handle(*args, **options)
zodiac-web_1  |   File "/code/zodiac/gateway/management/commands/setup_services.py", line 254, in handle
zodiac-web_1  |     if not Source.objects.filter(apikey=source['apikey'], username=source['username']).exists():
zodiac-web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
zodiac-web_1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
zodiac-web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 941, in filter
zodiac-web_1  |     return self._filter_or_exclude(False, args, kwargs)
zodiac-web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
zodiac-web_1  |     clone._filter_or_exclude_inplace(negate, args, kwargs)
zodiac-web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
zodiac-web_1  |     self._query.add_q(Q(*args, **kwargs))
zodiac-web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1393, in add_q
zodiac-web_1  |     clause, _ = self._add_q(q_object, self.used_aliases)
zodiac-web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1415, in _add_q
zodiac-web_1  |     split_subq=split_subq, check_filterable=check_filterable,
zodiac-web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1286, in build_filter
zodiac-web_1  |     lookups, parts, reffed_expression = self.solve_lookup_type(arg)
zodiac-web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1112, in solve_lookup_type
zodiac-web_1  |     _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
zodiac-web_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1540, in names_to_path
zodiac-web_1  |     "Choices are: %s" % (name, ", ".join(available)))
zodiac-web_1  | django.core.exceptions.FieldError: Cannot resolve keyword 'username' into field. Choices are: apikey, id, serviceregistry, user, user_id
```
I ran `docker-compose down -v` before `docker-compose up --build`. And while I was able to stand the application up, the `gateway` tests failed.

**Comment by helrond** [comment]
OK this should work.

**Comment by bonniegee** [comment]
Can confirm I was able to get it up and running with no issues, and all tests passed.

**Review by p-galligan — APPROVED** [review]

**Comment by HaSistrunk** [comment]
Working fine for me as well!

**Review by HaSistrunk — APPROVED** [review]

**Pull request merged**
