### PR TITLE
Updating CI configs

### PR DESCRIPTION
**Pull request by helrond**
- Updates Travis CI configs
- Updates README
- Updates dependencies

### CODE REVIEW

**Review by bonniegee — APPROVED** [review]
Looks good!

**Comment by p-galligan** [comment]
@helrond I noticed that dev isn't protected against deletion. Or, if it is, the check mark doesn't appear for me.

**Comment by helrond** [comment]
@p-galligan hmmm there is a branch protection rule in place and the branch views shows me a lock icon.

**Comment by p-galligan** [comment]
> @p-galligan hmmm there is a branch protection rule in place and the branch views shows me a lock icon.

Yeah, I see rules being in place too, but I guess I can't see the specifics of what those rules are from the branch settings. I'll check the branch view in the future to confirm.

**Review by HaSistrunk — APPROVED** [review]

**Review by p-galligan — APPROVED** [review]

**Pull request merged**
